config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :tones
  resources :musicstuffs
  root 'welcome#index'
  resources :notes
  resources :instruments
  resources :hasmanydanses
  resources :danses do
    collection do
      post 'mydanse'
    end
  end
  resources :pieces do
    member do
      get "editpiece"
    end
  end
  devise_for :users
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/danse.rb
class Danse < ApplicationRecord
end

app/models/hasmanydanse.rb
class Hasmanydanse < ApplicationRecord
  belongs_to :piece
  belongs_to :danse
  
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :tone, optional: true

end

app/models/musicstuff.rb
class Musicstuff < ApplicationRecord
  def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
    end
    write_attribute(:image,uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/piece.rb
class Piece < ApplicationRecord
  has_many :hasmanydanses
  def mycontent
    str=""
    if numero.length > 0
      str+= "que signifie "+numero+" ?"
    end
    
    str
  end
end

app/models/tone.rb
class Tone < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :tone, optional: true
  def yt?
  yt_regexp = /^(?:http:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]*)/
  yt_regexp.match(link)
  end
  def vimeo?
  vimeo_regexp = /^(?:http:\/\/)?(?:www\.)?vimeo\.com\/(\d+)/
  vimeo_regexp.match(link)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:name)
    end
end

app/controllers/tones_controller.rb
class TonesController < ApplicationController
  before_action :set_tone, only: %i[ show edit update destroy ]

  # GET /tones or /tones.json
  def index
    @tones = Tone.all+[Tone.new(name: "aucun")]
    @tone=Tone.find_by(name:params[:tone])

    if params[:tone]=="aucun"
      @videos=Video.all.where(tone_id: nil)
    elsif @tone

      @videos=Video.all.where(tone_id: @tone.id)
    else
      @videos=[]
    end
  end

  # GET /tones/1 or /tones/1.json
  def show
    @tones = Tone.all+[Tone.new(name: "aucun")]
  end

  # GET /tones/new
  def new
    @tone = Tone.new
  end

  # GET /tones/1/edit
  def edit
  end

  # POST /tones or /tones.json
  def create
    @tone = Tone.new(tone_params)

    respond_to do |format|
      if @tone.save
        format.html { redirect_to tone_url(@tone), notice: "Tone was successfully created." }
        format.json { render :show, status: :created, location: @tone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tones/1 or /tones/1.json
  def update
    respond_to do |format|
      if @tone.update(tone_params)
        format.html { redirect_to tone_url(@tone), notice: "Tone was successfully updated." }
        format.json { render :show, status: :ok, location: @tone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tones/1 or /tones/1.json
  def destroy
    @tone.destroy

    respond_to do |format|
      format.html { redirect_to tones_url, notice: "Tone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tone
      @tone = Tone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tone_params
      params.require(:tone).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/danses_helper.rb
module DansesHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/musicstuffs_helper.rb
module MusicstuffsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/tones_helper.rb
module TonesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p>
    <strong>Name:</strong>
    <%= note.name %>
  </p>

</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notes</h1>

<div id="notes">
  <% @notes.each do |note| %>
    <%= render note %>
    <p>
      <%= link_to "Show this note", note %>
    </p>
  <% end %>
</div>

<%= link_to "New note", new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
</div>

app/views/tones/_form.html.erb
<%= form_with(model: tone) do |form| %>
  <% if tone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tone.errors.count, "error") %> prohibited this tone from being saved:</h2>

      <ul>
        <% tone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tones/_tone.html.erb
<div id="<%= dom_id tone %>">
  <p>
    <strong>Name:</strong>
    <%= tone.name %>
  </p>

</div>

app/views/tones/edit.html.erb
<h1>Editing tone</h1>

<%= render "form", tone: @tone %>

<br>

<div>
  <%= link_to "Show this tone", @tone %> |
  <%= link_to "Back to tones", tones_path %>
</div>

app/views/tones/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tones</h1>

<div id="tones">
  <p class="mytones"><%@tones.each do |t|%><span><%=link_to t.name,tones_path(tone: t.name)%></span><%end%></p>
</div>
<%if params[:tone].to_s.length > 0%>
  <%if @tone %>
  <%= render @tone %>
<%else%>
  <p>aucune tonalité</p>
<%end%>

  <%if @videos.length > 0%>
    <%=render @videos%>
  <%else%>
        <p>aucune vidéo dans cette tonalite</p>
      <%end%>
    <%else%>
      <p>choisissez une tonalité</p>
<%end%>


<%= link_to "New tone", new_tone_path %>

app/views/tones/new.html.erb
<h1>New tone</h1>

<%= render "form", tone: @tone %>

<br>

<div>
  <%= link_to "Back to tones", tones_path %>
</div>

app/views/tones/show.html.erb
<p style="color: green"><%= notice %></p>
<p class="mytones"><%@tones.each do |t|%><span><%=link_to t.name,tones_path(tone: t.name)%></span><%end%></p>

<%= render @tone %>
<%if @videos.length > 0%>
<%=render @videos%>
<%else%>
  <p>aucune vidéo dans cette tonalite</p>
<%end%>

<div>
  <%= link_to "Edit this tone", edit_tone_path(@tone) %> |
  <%= link_to "Back to tones", tones_path %>

  <%= button_to "Destroy this tone", @tone, method: :delete %>
</div>