config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :tones
  resources :musicstuffs
  root 'welcome#index'
  resources :notes
  resources :instruments
  resources :hasmanydanses
  resources :danses do
    collection do
      post 'mydanse'
    end
  end
  resources :pieces do
    member do
      get "editpiece"
    end
  end
  devise_for :users
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/danse.rb
class Danse < ApplicationRecord
end

app/models/hasmanydanse.rb
class Hasmanydanse < ApplicationRecord
  belongs_to :piece
  belongs_to :danse
  
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :tone, optional: true

end

app/models/musicstuff.rb
class Musicstuff < ApplicationRecord
  def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
    end
    write_attribute(:image,uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/piece.rb
class Piece < ApplicationRecord
  has_many :hasmanydanses
  def mycontent
    str=""
    if numero.length > 0
      str+= "que signifie "+numero+" ?"
    end
    
    str
  end
end

app/models/tone.rb
class Tone < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :tone, optional: true
  def yt?
  yt_regexp = /^(?:http:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]*)/
  yt_regexp.match(link)
  end
  def vimeo?
  vimeo_regexp = /^(?:http:\/\/)?(?:www\.)?vimeo\.com\/(\d+)/
  vimeo_regexp.match(link)
  end

end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: %i[ show edit update destroy ]

  # GET /instruments or /instruments.json
  def index
    @instruments = Instrument.all
  end

  # GET /instruments/1 or /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments or /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to instrument_url(@instrument), notice: "Instrument was successfully created." }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1 or /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to instrument_url(@instrument), notice: "Instrument was successfully updated." }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1 or /instruments/1.json
  def destroy
    @instrument.destroy

    respond_to do |format|
      format.html { redirect_to instruments_url, notice: "Instrument was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instrument_params
      params.require(:instrument).permit(:name, :familier,:tone_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/danses_helper.rb
module DansesHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/musicstuffs_helper.rb
module MusicstuffsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/tones_helper.rb
module TonesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/instruments/_form.html.erb
<%= form_with(model: instrument) do |form| %>
  <% if instrument.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
        <% instrument.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :familier, style: "display: block" %>
    <%= form.text_field :familier %>
  </div>
  <div>
    <%= form.label :tone_id, style: "display: block" %>
    <%= form.select :tone_id, options_for_select(Tone.all.collect{|g|[g.name,g.id]}), {include_blank: true} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/instruments/_instrument.html.erb
<div id="<%= dom_id instrument %>">
  <p>
    <strong>Name:</strong>
    <%= instrument.name %>
  </p>

  <p>
    <strong>Familier:</strong>
    <%= instrument.familier %>
  </p>
    <strong>tonalite:</strong>
    <%= instrument.tone.try(:name) %>

</div>

app/views/instruments/edit.html.erb
<h1>Editing instrument</h1>

<%= render "form", instrument: @instrument %>

<br>

<div>
  <%= link_to "Show this instrument", @instrument %> |
  <%= link_to "Back to instruments", instruments_path %>
</div>

app/views/instruments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Instruments</h1>

<div id="instruments">
  <% @instruments.each do |instrument| %>
    <%= render instrument %>
    <p>
      <%= link_to "Show this instrument", instrument %>
    </p>
  <% end %>
</div>

<%= link_to "New instrument", new_instrument_path %>

app/views/instruments/new.html.erb
<h1>New instrument</h1>

<%= render "form", instrument: @instrument %>

<br>

<div>
  <%= link_to "Back to instruments", instruments_path %>
</div>

app/views/instruments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @instrument %>

<div>
  <%= link_to "Edit this instrument", edit_instrument_path(@instrument) %> |
  <%= link_to "Back to instruments", instruments_path %>

  <%= button_to "Destroy this instrument", @instrument, method: :delete %>
</div>