config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :tones
  resources :musicstuffs
  root 'welcome#index'
  resources :notes
  resources :instruments
  resources :hasmanydanses
  resources :danses do
    collection do
      post 'mydanse'
    end
  end
  resources :pieces do
    member do
      get "editpiece"
    end
  end
  devise_for :users
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/danse.rb
class Danse < ApplicationRecord
end

app/models/hasmanydanse.rb
class Hasmanydanse < ApplicationRecord
  belongs_to :piece
  belongs_to :danse
  
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :tone, optional: true

end

app/models/musicstuff.rb
class Musicstuff < ApplicationRecord
  def image=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
    end
    write_attribute(:image,uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/piece.rb
class Piece < ApplicationRecord
  has_many :hasmanydanses
  def mycontent
    str=""
    if numero.length > 0
      str+= "que signifie "+numero+" ?"
    end
    
    str
  end
end

app/models/tone.rb
class Tone < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :tone, optional: true
  def yt?
  yt_regexp = /^(?:http:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]*)/
  yt_regexp.match(link)
  end
  def vimeo?
  vimeo_regexp = /^(?:http:\/\/)?(?:www\.)?vimeo\.com\/(\d+)/
  vimeo_regexp.match(link)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/danses_helper.rb
module DansesHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/tones_helper.rb
module TonesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mynewapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%=link_to "BIENVENUE ","/"%>  |
      <%=link_to "voir tous les morceaux ","/pieces"%>  |
      <%=link_to "voir toutes les danses ","/danses"%>  |
      <%=link_to "voir tous les instruments de musique ",instruments_path%>  |
      <%=link_to "ajouter des trucs sur la musique ",musicstuffs_path%>  |
      <%=link_to "voir toutes les tonalités",tones_path%>  |
      <%=link_to "voir toutes les videos",videos_path%>  |
      <%=link_to "connexion","/users/sign_in"%>  |
          <%=link_to "inscription","/users/sign_up"%>  |
              <%if user_signed_in?%>
                      <%=button_to "deconnexion",destroy_user_session_path,method: :delete%> |
                        <%end%>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="/assets/<%=params[:controller]%>.js" type="text/javascript"/>
  </body>
</html>